### ISSUE TITLE
Recompile Gem and Update Version

### ISSUE THREAD

**Issue by alexggordon** [chrishough/cdnjs-rails#5]
Hey Chris! 

So it looks like since [this](https://github.com/chrishough/cdnjs-rails/blob/1983c8f9643f3cb4cd34cad8ad3bb11a0641458d/lib/cdnjs-rails/view_helpers.rb#L3) pull request, the .gem binary has not been recompiled and pushed to [rubygems](https://rubygems.org/gems/cdnjs-rails/versions/1.0.0). I believe the correct thing to do would be to update the gem version with the pull request mentioned above, and push out a new binary to rubygems. 

Currently, for local development, I'm compiling the gem myself, but it would be nice to have the most recent updates on ruby gems. Let me know if you'd like me to create a pull request with the new version. 

Thanks!

**Comment by chrishough** [comment]
@alexggordon sure thing man, go for it. I am happy to accept your PR to fix this.

**Comment by mvarrieur** [comment]
:+1: I'd never contributed to a gem before so wasn't sure of the process of getting it onto rubygems. Thanks @alexggordon!

**Comment by alexggordon** [comment]
No problem @mvarrieur!

**Comment by alexggordon** [comment]
Closed in favor of the [pull request](https://github.com/chrishough/cdnjs-rails/pull/6).
