### ISSUE TITLE
v1.0.1 gem?

### ISSUE THREAD

**Issue by layflags** [chrishough/cdnjs-rails#7]
Hi @chrishough, like your gem! When do you consider publishing v1.0.1?

**Comment by chrishough** [comment]
I will be working to get out a new version this week with all patches.

**Comment by layflags** [comment]
Thx :)

**Comment by chrishough** [comment]
I just updated the gem and pushed the 1.0.1 release up to RubyGems. Sorry this took so damn long, that was my bad. Happy Holidays.

**Comment by layflags** [comment]
Thx Chris! Wish you a merry :christmas_tree:
